version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8081:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"    
    
  web:
    build: .
    ports:
      - 8080:5000
    depends_on:
      - db